//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TS.Resources.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TS.Resources.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You already answered this questionnaire!.
        /// </summary>
        internal static string answers_already {
            get {
                return ResourceManager.GetString("answers_already", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have successfully answer!.
        /// </summary>
        internal static string answers_success {
            get {
                return ResourceManager.GetString("answers_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your email, please!.
        /// </summary>
        internal static string email_see {
            get {
                return ResourceManager.GetString("email_see", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0} has been successfully created!.
        /// </summary>
        internal static string group_created {
            get {
                return ResourceManager.GetString("group_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0} has been successfully deleted!.
        /// </summary>
        internal static string group_deleted {
            get {
                return ResourceManager.GetString("group_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This group does not exist!.
        /// </summary>
        internal static string group_does_not_exist {
            get {
                return ResourceManager.GetString("group_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group {0} has been successfully modified!.
        /// </summary>
        internal static string group_edited {
            get {
                return ResourceManager.GetString("group_edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image has been successfully uploaded!.
        /// </summary>
        internal static string image_uploaded {
            get {
                return ResourceManager.GetString("image_uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Null.
        /// </summary>
        internal static string install_doesnt_exist_datas {
            get {
                return ResourceManager.GetString("install_doesnt_exist_datas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exist.
        /// </summary>
        internal static string install_exist_datas {
            get {
                return ResourceManager.GetString("install_exist_datas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred!Please ask for support!.
        /// </summary>
        internal static string install_failure {
            get {
                return ResourceManager.GetString("install_failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database was successfully installed!.
        /// </summary>
        internal static string install_success {
            get {
                return ResourceManager.GetString("install_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!You are not registered in database!.
        /// </summary>
        internal static string login_error {
            get {
                return ResourceManager.GetString("login_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in successfully!.
        /// </summary>
        internal static string login_success {
            get {
                return ResourceManager.GetString("login_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        internal static string message_success {
            get {
                return ResourceManager.GetString("message_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been successfully changed!.
        /// </summary>
        internal static string password_changed {
            get {
                return ResourceManager.GetString("password_changed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question has been successfully created!.
        /// </summary>
        internal static string question_created {
            get {
                return ResourceManager.GetString("question_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question has been successfully deleted!.
        /// </summary>
        internal static string question_deleted {
            get {
                return ResourceManager.GetString("question_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This question does not exist!.
        /// </summary>
        internal static string question_does_not_exist {
            get {
                return ResourceManager.GetString("question_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question has been successfully modified!.
        /// </summary>
        internal static string question_edited {
            get {
                return ResourceManager.GetString("question_edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire has been successfully created!.
        /// </summary>
        internal static string questionnaire_created {
            get {
                return ResourceManager.GetString("questionnaire_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questionnaire has been successfully deleted!.
        /// </summary>
        internal static string questionnaire_deleted {
            get {
                return ResourceManager.GetString("questionnaire_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This questionnaire does not exist!.
        /// </summary>
        internal static string questionnaire_does_not_exist {
            get {
                return ResourceManager.GetString("questionnaire_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic successfully deleted!.
        /// </summary>
        internal static string statistic_delete_success {
            get {
                return ResourceManager.GetString("statistic_delete_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This statistic does not exist!.
        /// </summary>
        internal static string statistic_does_not_exist {
            get {
                return ResourceManager.GetString("statistic_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University has been successfully created!.
        /// </summary>
        internal static string university_created {
            get {
                return ResourceManager.GetString("university_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University has been successfully deleted!.
        /// </summary>
        internal static string university_deleted {
            get {
                return ResourceManager.GetString("university_deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This university does not exist!.
        /// </summary>
        internal static string university_does_not_exist {
            get {
                return ResourceManager.GetString("university_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University has been successfully modified!.
        /// </summary>
        internal static string university_edited {
            get {
                return ResourceManager.GetString("university_edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been successfully created!.
        /// </summary>
        internal static string user_created {
            get {
                return ResourceManager.GetString("user_created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been successfully disabled!.
        /// </summary>
        internal static string user_disabled {
            get {
                return ResourceManager.GetString("user_disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been successfully modified!.
        /// </summary>
        internal static string user_edited {
            get {
                return ResourceManager.GetString("user_edited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user has no assigned answers!.
        /// </summary>
        internal static string user_no_answers {
            get {
                return ResourceManager.GetString("user_no_answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user does not exist!.
        /// </summary>
        internal static string user_not_exist {
            get {
                return ResourceManager.GetString("user_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not registered in database!.
        /// </summary>
        internal static string user_not_in_database {
            get {
                return ResourceManager.GetString("user_not_in_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password or username incorrect!.
        /// </summary>
        internal static string user_wrong {
            get {
                return ResourceManager.GetString("user_wrong", resourceCulture);
            }
        }
    }
}
